// import {MouseEventInterface} from '../interfaces/MouseEventInterface'

import { reactive } from 'vue'

export default function () {
    let keyboardModel = {
        "Escape": false,

        "F1": false,
        "F2": false,
        "F3": false,
        "F4": false,
        "F5": false,
        "F6": false,
        "F7": false,
        "F8": false,
        "F9": false,
        "F10": false,
        "F11": false,
        "F12": false,

        "Digit1": false,
        "Digit2": false,
        "Digit3": false,
        "Digit4": false,
        "Digit5": false,
        "Digit6": false,
        "Digit7": false,
        "Digit8": false,
        "Digit9": false,
        "Digit0": false,

        "KeyA": false,
        "KeyB": false,
        "KeyC": false,
        "KeyD": false,
        "KeyE": false,
        "KeyF": false,
        "KeyG": false,
        "KeyH": false,
        "KeyI": false,
        "KeyJ": false,
        "KeyK": false,
        "KeyL": false,
        "KeyM": false,
        "KeyN": false,
        "KeyO": false,
        "KeyP": false,
        "KeyQ": false,
        "KeyR": false,
        "KeyS": false,
        "KeyT": false,
        "KeyU": false,
        "KeyV": false,
        "KeyW": false,
        "KeyX": false,
        "KeyY": false,
        "KeyZ": false,

        "Backquote": false,
        "Minus": false,
        "Equal": false,
        "Backspace": false,
        "Tab": false,
        "CapsLock": false,
        "ShiftLeft": false,
        "ControlLeft": false,
        "MetaLeft": false,
        "AltLeft": false,
        "Enter": false,
        "ShiftRight": false,
        "ControlRight": false,
        "ContextMenu": false,
        "MetaRight": false,
        "AltRight": false,
        "Space": false,

        "PrintScreen": false,
        "ScrollLock": false,
        "Pause": false,

        "Insert": false,
        "Delete": false,
        "Home": false,
        "End": false,
        "PageUp": false,
        "PageDown": false,

        "ArrowUp": false,
        "ArrowDown": false,
        "ArrowLeft": false,
        "ArrowRight": false,

        "NumLock": false,
        "NumpadAdd": false,
        "NumpadSubtract": false,
        "NumpadMultiply": false,
        "NumpadDivide": false,
        "NumpadEnter": false,

        "Numpad1": false,
        "Numpad2": false,
        "Numpad3": false,
        "Numpad4": false,
        "Numpad5": false,
        "Numpad6": false,
        "Numpad7": false,
        "Numpad8": false,
        "Numpad9": false,
        "Numpad0": false,
        "NumpadDecimal": false,
    }
    return {
        keyboardModel: reactive(keyboardModel)
    }
}